server:
  port: 8763

spring:
  application:
    name: service-hi

eureka:
  client:
    service-url:
      deafaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"